staticSites:
  - name: parceiro-ia-site
    branch: main
    rootDir: .
    buildCommand: npm ci && npm run build
    publishPath: dist
    autoDeploy: true
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: "20"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
